export const siteConfig = {
  name: 'Devisyn',
  description: 'Custom Software Development & Digital Solutions',
  url: 'https://devisyn.com',
  ogImage: 'https://devisyn.com/og-image.jpg',
  links: {
    twitter: 'https://twitter.com/devisyn',
    github: 'https://github.com/devisyn',
    linkedin: 'https://linkedin.com/company/devisyn',
  },
  features: {
    showPricing: false, // Set to false as agencies typically don't show pricing
    showBlog: true,
    showPortfolio: true,
    showServices: true,
    showAbout: true,
    showContact: true,
  },
  company: {
    name: 'Devisyn',
    founded: '2020',
    location: 'San Francisco, CA',
    email: 'contact@devisyn.com',
    phone: '+1 (929) 699-5923',
    address: '123 Tech Street, San Francisco, CA 94105',
  },
  social: {
    twitter: '@devisyn',
    linkedin: 'devisyn',
    github: 'devisyn',
  },
  navigation: [
    { name: 'Home', href: '/' },
    { name: 'About', href: '/about' },
    { name: 'Services', href: '/services' },
    { name: 'Portfolio', href: '/portfolio' },
    { name: 'Blog', href: '/blog' },
    { name: 'Contact', href: '/contact' },
  ],
  services: [
    {
      title: 'Custom Software Development',
      description: 'Tailored software solutions that address your unique business needs.',
      icon: '💻',
      features: [
        'Enterprise Applications',
        'API Development',
        'Legacy System Modernization',
        'Integration Services',
      ],
    },
    {
      title: 'Web Applications',
      description: 'Modern, scalable web applications built with cutting-edge technologies.',
      icon: '🌐',
      features: [
        'Single Page Applications',
        'Progressive Web Apps',
        'E-commerce Solutions',
        'Content Management Systems',
      ],
    },
    {
      title: 'Mobile Solutions',
      description: 'Native and cross-platform mobile applications for iOS and Android.',
      icon: '📱',
      features: [
        'iOS Development',
        'Android Development',
        'React Native Apps',
        'Flutter Applications',
      ],
    },
    {
      title: 'Cloud Solutions',
      description: 'Scalable cloud infrastructure and deployment solutions.',
      icon: '☁️',
      features: [
        'Cloud Migration',
        'DevOps & CI/CD',
        'Cloud Architecture',
        'Serverless Solutions',
      ],
    },
    {
      title: 'AI & Machine Learning',
      description: 'Intelligent solutions powered by advanced AI and ML technologies.',
      icon: '🤖',
      features: [
        'Machine Learning Models',
        'Natural Language Processing',
        'Computer Vision',
        'Predictive Analytics',
      ],
    },
    {
      title: 'Cybersecurity',
      description: 'Comprehensive security solutions to protect your digital assets.',
      icon: '🔒',
      features: [
        'Security Audits',
        'Penetration Testing',
        'Compliance & GDPR',
        'Security Consulting',
      ],
    },
  ],
  technologies: [
    'React',
    'Next.js',
    'Node.js',
    'Python',
    'TypeScript',
    'AWS',
    'Docker',
    'Kubernetes',
    'MongoDB',
    'PostgreSQL',
    'GraphQL',
    'TensorFlow',
    'React Native',
    'Flutter',
    'Django',
    'FastAPI',
  ],
  testimonials: [
    {
      name: 'John Smith',
      role: 'CTO at TechCorp',
      content: 'Devisyn transformed our business with their innovative solutions. Their team\'s expertise and dedication are unmatched.',
      image: '/testimonials/john-smith.jpg',
    },
    {
      name: 'Sarah Johnson',
      role: 'Product Manager at InnovateCo',
      content: 'Working with Devisyn was a game-changer for our product development. They delivered beyond our expectations.',
      image: '/testimonials/sarah-johnson.jpg',
    },
    {
      name: 'Michael Chen',
      role: 'CEO at StartupX',
      content: 'Devisyn\'s team helped us scale our platform efficiently. Their technical expertise and business understanding are exceptional.',
      image: '/testimonials/michael-chen.jpg',
    },
  ],
  stats: [
    { label: 'Projects Completed', value: '150+' },
    { label: 'Happy Clients', value: '50+' },
    { label: 'Team Members', value: '25+' },
    { label: 'Countries Served', value: '10+' },
  ],
}; 